version: '3.8'

services:
  app:
    build: .
    container_name: taskmanager_app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      - APP_ENV=production
    depends_on:
      - db
    networks:
      - taskmanager

  webserver:
    image: nginx:alpine
    container_name: taskmanager_nginx
    restart: unless-stopped
    ports:
      - "8090:80"
    volumes:
      - app_code:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - taskmanager

  db:
    image: mysql:8.0
    container_name: taskmanager_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: task_management
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: taskuser
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - taskmanager

networks:
  taskmanager:
    driver: bridge

volumes:
  dbdata:
    driver: local
  app_code:
    driver: local
